language: android

git:
  depth: 1

env:
  global:
    # General information:
    - ANDROID_ABI=armeabi-v7a # x86 or armeabi-v7a. At this time, Travis can not run android-x86
    - ANDROID_TARGET=android-23
    - ADB_INSTALL_TIMEOUT=10 # minutes (2 minutes by default)

    ##### Client project env #####

    - ANDROID_DIR=client
    - ANDROID_PROJECT_NAME=IMDBTopMovies2
    - BUILD_TYPE=travisCI
    - RELEASE_PATH_FILE=build/outputs/apk

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.0

    # The SDK version used to compile your project
    - $ANDROID_TARGET

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-$ANDROID_ABI-android-22

before_install:
  - chmod -R ugo+x travis-script/
  - source ./travis-script/install-dependencies.sh

script:
  # Run client test
  - ./travis-script/run-client-test.sh
  
  # Run server test
  - ./travis-script/run-server-test.sh
